server:
  servlet:
    context-path: /hanyu-be
  port: 8080
spring:
  banner:
    location: classpath:/config/banner.txt
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/hanyu-db
    username: sa
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

hu:
  public-apis:
    path:
      - /api/settings/**
      - /api/auth/**
      - /swagger-ui/**
      - /swagger-ui/**/**
      - /v3/api-docs/**
