import { Word } from "../models/Word";

const ListWords: Word[] = [
  {
    id: 1,
    word: "你好",
    pinyin: "nǐ hǎo",
    meaning: "hello",
    noteBookId: 1,
  },
  {
    id: 2,
    word: "谢谢",
    pinyin: "xiè xiè",
    meaning: "thank you",
    noteBookId: 1,
  },
  {
    id: 3,
    word: "是",
    pinyin: "shì",
    meaning: "is, am, are",
    noteBookId: 1,
  },
  {
    id: 4,
    word: "不",
    pinyin: "bù",
    meaning: "not",
    noteBookId: 1,
  },
  {
    id: 5,
    word: "吗",
    pinyin: "ma",
    meaning: "question particle",
    noteBookId: 1,
  },
  {
    id: 6,
    word: "中国",
    pinyin: "zhōng guó",
    meaning: "China",
    noteBookId: 1,
  },
  {
    id: 7,
    word: "我",
    pinyin: "wǒ",
    meaning: "I, me",
    noteBookId: 1,
  },
  {
    id: 8,
    word: "很",
    pinyin: "hěn",
    meaning: "very",
    noteBookId: 1,
  },
  {
    id: 9,
    word: "也",
    pinyin: "yě",
    meaning: "also, too",
    noteBookId: 1,
  },
  {
    id: 10,
    word: "是的",
    pinyin: "shì de",
    meaning: "yes",
    noteBookId: 1,
  },
  {
    id: 11,
    word: "不是",
    pinyin: "bú shì",
    meaning: "no",
    noteBookId: 1,
  },
  {
    id: 12,
    word: "朋友",
    pinyin: "péng yǒu",
    meaning: "friend",
    noteBookId: 1,
  },
  {
    id: 13,
    word: "家",
    pinyin: "jiā",
    meaning: "family, home",
    noteBookId: 1,
  },
  {
    id: 14,
    word: "有",
    pinyin: "yǒu",
    meaning: "to have",
    noteBookId: 1,
  },
  {
    id: 15,
    word: "没关系",
    pinyin: "méi guān xi",
    meaning: "it's okay",
    noteBookId: 1,
  },
  {
    id: 16,
    word: "老师",
    pinyin: "lǎo shī",
    meaning: "teacher",
    noteBookId: 1,
  },
  {
    id: 17,
    word: "学生",
    pinyin: "xué shēng",
    meaning: "student",
    noteBookId: 1,
  },
  {
    id: 18,
    word: "工作",
    pinyin: "gōng zuò",
    meaning: "work",
    noteBookId: 1,
  },
  {
    id: 19,
    word: "喜欢",
    pinyin: "xǐ huān",
    meaning: "to like",
    noteBookId: 1,
  },
  {
    id: 20,
    word: "吃",
    pinyin: "chī",
    meaning: "to eat",
    noteBookId: 1,
  },
  {
    id: 21,
    word: "坐",
    pinyin: "zuò",
    meaning: "to sit",
    noteBookId: 2,
  },
  {
    id: 22,
    word: "喜欢",
    pinyin: "xǐ huān",
    meaning: "to like",
    noteBookId: 2,
  },
  {
    id: 23,
    word: "认识",
    pinyin: "rèn shí",
    meaning: "to know, to recognize",
    noteBookId: 2,
  },
  {
    id: 24,
    word: "朋友",
    pinyin: "péng yǒu",
    meaning: "friend",
    noteBookId: 2,
  },
  {
    id: 25,
    word: "一起",
    pinyin: "yī qǐ",
    meaning: "together",
    noteBookId: 2,
  },
  {
    id: 26,
    word: "想",
    pinyin: "xiǎng",
    meaning: "to want, to think",
    noteBookId: 2,
  },
  {
    id: 27,
    word: "去",
    pinyin: "qù",
    meaning: "to go",
    noteBookId: 2,
  },
  {
    id: 28,
    word: "工作",
    pinyin: "gōng zuò",
    meaning: "to work",
    noteBookId: 2,
  },
  {
    id: 29,
    word: "买",
    pinyin: "mǎi",
    meaning: "to buy",
    noteBookId: 2,
  },
  {
    id: 30,
    word: "时间",
    pinyin: "shí jiān",
    meaning: "time",
    noteBookId: 2,
  },
  {
    id: 31,
    word: "见面",
    pinyin: "jiàn miàn",
    meaning: "to meet",
    noteBookId: 2,
  },
  {
    id: 32,
    word: "帮助",
    pinyin: "bāng zhù",
    meaning: "to help",
    noteBookId: 2,
  },
  {
    id: 33,
    word: "学习",
    pinyin: "xué xí",
    meaning: "to study",
    noteBookId: 2,
  },
  {
    id: 34,
    word: "觉得",
    pinyin: "jué de",
    meaning: "to think, to feel",
    noteBookId: 2,
  },
  {
    id: 35,
    word: "高兴",
    pinyin: "gāo xìng",
    meaning: "happy",
    noteBookId: 2,
  },
  {
    id: 36,
    word: "电影",
    pinyin: "diàn yǐng",
    meaning: "movie",
    noteBookId: 3,
  },
  {
    id: 37,
    word: "机会",
    pinyin: "jī huì",
    meaning: "opportunity",
    noteBookId: 3,
  },
  {
    id: 38,
    word: "出现",
    pinyin: "chū xiàn",
    meaning: "to appear",
    noteBookId: 3,
  },
  {
    id: 39,
    word: "同意",
    pinyin: "tóng yì",
    meaning: "to agree",
    noteBookId: 3,
  },
  {
    id: 40,
    word: "继续",
    pinyin: "jì xù",
    meaning: "to continue",
    noteBookId: 3,
  },
  {
    id: 41,
    word: "改变",
    pinyin: "gǎi biàn",
    meaning: "to change",
    noteBookId: 3,
  },
  {
    id: 42,
    word: "重要",
    pinyin: "zhòng yào",
    meaning: "important",
    noteBookId: 3,
  },
  {
    id: 43,
    word: "成功",
    pinyin: "chéng gōng",
    meaning: "success",
    noteBookId: 3,
  },
  {
    id: 44,
    word: "提高",
    pinyin: "tí gāo",
    meaning: "to improve",
    noteBookId: 3,
  },
  {
    id: 45,
    word: "选择",
    pinyin: "xuǎn zé",
    meaning: "to choose",
    noteBookId: 3,
  },
  {
    id: 46,
    word: "经济",
    pinyin: "jīng jì",
    meaning: "economy",
    noteBookId: 4,
  },
  {
    id: 47,
    word: "科学",
    pinyin: "kē xué",
    meaning: "science",
    noteBookId: 4,
  },
  {
    id: 48,
    word: "环境",
    pinyin: "huán jìng",
    meaning: "environment",
    noteBookId: 4,
  },
  {
    id: 49,
    word: "文化",
    pinyin: "wén huà",
    meaning: "culture",
    noteBookId: 4,
  },
  {
    id: 50,
    word: "关心",
    pinyin: "guān xīn",
    meaning: "to care",
    noteBookId: 4,
  },
  {
    id: 51,
    word: "生活",
    pinyin: "shēng huó",
    meaning: "life",
    noteBookId: 4,
  },
  {
    id: 52,
    word: "发展",
    pinyin: "fā zhǎn",
    meaning: "to develop",
    noteBookId: 4,
  },
  {
    id: 53,
    word: "重视",
    pinyin: "zhòng shì",
    meaning: "to attach importance to",
    noteBookId: 4,
  },
  {
    id: 54,
    word: "技术",
    pinyin: "jì shù",
    meaning: "technology",
    noteBookId: 4,
  },
  {
    id: 55,
    word: "能力",
    pinyin: "néng lì",
    meaning: "ability",
    noteBookId: 4,
  },
  {
    id: 56,
    word: "难道",
    pinyin: "nán dào",
    meaning: "could it be that, do you mean to say",
    noteBookId: 5,
  },
  {
    id: 57,
    word: "传真",
    pinyin: "chuán zhēn",
    meaning: "fax",
    noteBookId: 5,
  },
  {
    id: 58,
    word: "批评",
    pinyin: "pī píng",
    meaning: "to criticize, criticism",
    noteBookId: 5,
  },
  {
    id: 59,
    word: "兴奋",
    pinyin: "xīng fèn",
    meaning: "excitement, to be excited",
    noteBookId: 5,
  },
  {
    id: 60,
    word: "上网",
    pinyin: "shàng wǎng",
    meaning: "to go online, to surf the internet",
    noteBookId: 5,
  },
  {
    id: 61,
    word: "预习",
    pinyin: "yù xí",
    meaning: "to preview",
    noteBookId: 5,
  },
  {
    id: 62,
    word: "确实",
    pinyin: "què shí",
    meaning: "indeed, really",
    noteBookId: 5,
  },
  {
    id: 63,
    word: "继续",
    pinyin: "jì xù",
    meaning: "to continue",
    noteBookId: 5,
  },
  {
    id: 64,
    word: "经历",
    pinyin: "jīng lì",
    meaning: "experience",
    noteBookId: 5,
  },
  {
    id: 65,
    word: "过程",
    pinyin: "guò chéng",
    meaning: "process",
    noteBookId: 5,
  },
  {
    id: 66,
    word: "下雨",
    pinyin: "xià yǔ",
    meaning: "to rain",
    noteBookId: 5,
  },
  {
    id: 67,
    word: "脾气",
    pinyin: "pí qi",
    meaning: "temperament",
    noteBookId: 5,
  },
  {
    id: 68,
    word: "实际",
    pinyin: "shí jì",
    meaning: "actual, reality",
    noteBookId: 5,
  },
  {
    id: 69,
    word: "复杂",
    pinyin: "fù zá",
    meaning: "complex",
    noteBookId: 5,
  },
  {
    id: 70,
    word: "负责",
    pinyin: "fù zé",
    meaning: "to be responsible for",
    noteBookId: 5,
  },
  {
    id: 71,
    word: "疑问",
    pinyin: "yí wèn",
    meaning: "doubt, question",
    noteBookId: 6,
  },
  {
    id: 72,
    word: "研究",
    pinyin: "yán jiū",
    meaning: "research, to study",
    noteBookId: 6,
  },
  {
    id: 73,
    word: "规定",
    pinyin: "guī dìng",
    meaning: "regulation, to regulate",
    noteBookId: 6,
  },
  {
    id: 74,
    word: "指导",
    pinyin: "zhǐ dǎo",
    meaning: "guidance, to guide",
    noteBookId: 6,
  },
  {
    id: 75,
    word: "实行",
    pinyin: "shí xíng",
    meaning: "to implement",
    noteBookId: 6,
  },
  {
    id: 76,
    word: "组织",
    pinyin: "zǔ zhī",
    meaning: "organization, to organize",
    noteBookId: 6,
  },
  {
    id: 77,
    word: "意义",
    pinyin: "yì yì",
    meaning: "meaning, significance",
    noteBookId: 6,
  },
  {
    id: 78,
    word: "批准",
    pinyin: "pī zhǔn",
    meaning: "to approve",
    noteBookId: 6,
  },
  {
    id: 79,
    word: "讨论",
    pinyin: "tǎo lùn",
    meaning: "to discuss, discussion",
    noteBookId: 6,
  },
  {
    id: 80,
    word: "提醒",
    pinyin: "tí xǐng",
    meaning: "to remind, reminder",
    noteBookId: 6,
  },
  {
    id: 81,
    word: "旅行",
    pinyin: "lǚ xíng",
    meaning: "travel",
    noteBookId: 7,
  },
  {
    id: 82,
    word: "机票",
    pinyin: "jī piào",
    meaning: "airplane ticket",
    noteBookId: 7,
  },
  {
    id: 83,
    word: "酒店",
    pinyin: "jiǔ diàn",
    meaning: "hotel",
    noteBookId: 7,
  },
  {
    id: 84,
    word: "导游",
    pinyin: "dǎo yóu",
    meaning: "tour guide",
    noteBookId: 7,
  },
  {
    id: 85,
    word: "景点",
    pinyin: "jǐng diǎn",
    meaning: "tourist attraction",
    noteBookId: 7,
  },
  {
    id: 86,
    word: "交通",
    pinyin: "jiāo tōng",
    meaning: "transportation",
    noteBookId: 7,
  },
  {
    id: 87,
    word: "行李",
    pinyin: "xíng li",
    meaning: "luggage",
    noteBookId: 7,
  },
  {
    id: 88,
    word: "签证",
    pinyin: "qiān zhèng",
    meaning: "visa",
    noteBookId: 7,
  },
  {
    id: 89,
    word: "导航",
    pinyin: "dǎo háng",
    meaning: "navigation",
    noteBookId: 7,
  },
  {
    id: 90,
    word: "旅游",
    pinyin: "lǚ yóu",
    meaning: "tourism",
    noteBookId: 7,
  },
  {
    id: 91,
    word: "烹饪",
    pinyin: "pēng rèn",
    meaning: "cooking",
    noteBookId: 8,
  },
  {
    id: 92,
    word: "食材",
    pinyin: "shí cái",
    meaning: "ingredients",
    noteBookId: 8,
  },
  {
    id: 93,
    word: "炒菜",
    pinyin: "chǎo cài",
    meaning: "stir-fried dishes",
    noteBookId: 8,
  },
  {
    id: 94,
    word: "烤肉",
    pinyin: "kǎo ròu",
    meaning: "grilled meat",
    noteBookId: 8,
  },
  {
    id: 95,
    word: "蒸鱼",
    pinyin: "zhēng yú",
    meaning: "steamed fish",
    noteBookId: 8,
  },
  {
    id: 96,
    word: "烘焙",
    pinyin: "hōng bèi",
    meaning: "baking",
    noteBookId: 8,
  },
  {
    id: 97,
    word: "烹调",
    pinyin: "pēng tiáo",
    meaning: "culinary, cooking",
    noteBookId: 8,
  },
  {
    id: 98,
    word: "调味品",
    pinyin: "tiáo wèi pǐn",
    meaning: "seasoning",
    noteBookId: 8,
  },
  {
    id: 99,
    word: "炖汤",
    pinyin: "dùn tāng",
    meaning: "stewed soup",
    noteBookId: 8,
  },
  {
    id: 100,
    word: "切菜",
    pinyin: "qiē cài",
    meaning: "cutting vegetables",
    noteBookId: 8,
  },
];

export default ListWords;
